version: '3.4'

services:
  users-api:
    image: users-api
    container_name: users-api
    ports:
      - 8080:80
    depends_on: 
      - mysql
      - redis
    build:
      context: .
      dockerfile: Dockerfile
    environment: 
      MYSQL_CONNECTION: "Server=172.28.1.3;Uid=admin;Pwd=root;Database=users_db;"
      DB_NAME: "users_db"
      REDIS_CONNECTION: "172.28.1.4"
  mysql:
    image: mysql:5.7
    container_name: users-mysql
    restart: always
    ports: 
      - 3306:3306
    environment: 
      MYSQL_DATABASE: "users_db"
      MYSQL_USER: "admin"
      MYSQL_PASSWORD: "secret"
      MYSQL_ROOT_PASSWORD: "root"
    volumes: 
      - mysql_users:/var/lib/mysql
    networks:
      node_net:
        ipv4_address: 172.28.1.3
  redis:
    image: redis:alpine
    container_name: users-redis
    restart: always
    ports: 
      - 6379:6379
    volumes:
      - redis-users:/var/lib/redis
    networks: 
      node_net:
        ipv4_address: 172.28.1.4

volumes: 
  mysql_users:
  redis-users:

networks:
  node_net:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.1/16
