CREATE TABLE IF NOT EXISTS `users` (
  `Id` BINARY(16) NOT NULL,
  `Firstname` VARCHAR(128) NOT NULL,
  `Lastname` VARCHAR(128) NOT NULL,
  `Email` VARCHAR(256) UNIQUE NOT NULL,
  `DateOfBirth` DATE NOT NULL,
  `Age` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`Id`)
)